set_property IOSTANDARD LVCMOS33 [get_ports {cathode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports kbd_clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports raw_kbd_data]
set_property PACKAGE_PIN V7 [get_ports {cathode[0]}]
set_property PACKAGE_PIN U7 [get_ports {cathode[1]}]
set_property PACKAGE_PIN V5 [get_ports {cathode[2]}]
set_property PACKAGE_PIN U5 [get_ports {cathode[3]}]
set_property PACKAGE_PIN V8 [get_ports {cathode[4]}]
set_property PACKAGE_PIN U8 [get_ports {cathode[5]}]
set_property PACKAGE_PIN W6 [get_ports {cathode[6]}]
set_property PACKAGE_PIN W7 [get_ports {cathode[7]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN C17 [get_ports kbd_clk]
set_property PACKAGE_PIN B17 [get_ports raw_kbd_data]

set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {debugLED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debugLED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {debugLED[0]}]
set_property PACKAGE_PIN V14 [get_ports debugLED]

set_property PACKAGE_PIN U16 [get_ports {debugLED[0]}]
set_property PACKAGE_PIN E19 [get_ports {debugLED[1]}]
set_property PACKAGE_PIN U19 [get_ports {debugLED[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {bit_loc[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_loc[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_loc[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bit_loc[0]}]
set_property PACKAGE_PIN L1 [get_ports {bit_loc[3]}]
set_property PACKAGE_PIN P1 [get_ports {bit_loc[2]}]
set_property PACKAGE_PIN N3 [get_ports {bit_loc[1]}]
set_property PACKAGE_PIN P3 [get_ports {bit_loc[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports kbd_clk_debug]
set_property PACKAGE_PIN V13 [get_ports kbd_clk_debug]

set_property IOSTANDARD LVCMOS33 [get_ports dvld]
set_property PACKAGE_PIN V14 [get_ports dvld]
